---
- hosts: all
  become: yes
  tasks:
    - name: Add service accoubts
      user:
         name: "{{ item }}"
         comment: service account
         create_home: no
         shell: /usr/sbin/nologin
         state: present
      loop:
       - testuser1
       - testuser2